APIException: renamed to BitfinexClientException CommandException: renamed to BitfinexCommandException BitfinexCommands: introduced commands factory class JavaDocs: some of missing javadocs added Documentation: new paragraph around listeners